baseURL = "https://kimichan-studio.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "KimiChan Studio"
[markup.goldmark.renderer]
unsafe = true
